const catalogs = [
    {
        id: 1,
        name: 'Áo',
        link: '/shirt',
        icon: 'fa-solid fa-shirt',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 4,
        name: 'Âm thanh',
        link: '/speaker',
        icon: 'fa-solid fa-headphones',
        color: 'bg-purple-100 text-purple-600',
    },
    {
        id: 8,
        name: 'Công nghệ',
        link: '/technology',
        icon: 'fa-solid fa-cubes',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 9,
        name: 'Dụng cụ học tập',
        link: '/school-supply',
        icon: 'fa-solid fa-pencil',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 10,
        name: 'Đồ ăn',
        link: '/food',
        icon: 'fa-solid fa-burger',
        color: 'bg-blue-100 text-blue-600',
    },

    {
        id: 11,
        name: 'Đồ dùng',
        link: '/belonging',
        icon: 'fa-solid fa-cart-shopping',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 2,
        name: 'Gaming',
        link: '/gaming',
        icon: 'fa-solid fa-desktop',
        color: 'bg-purple-100 text-purple-600',
    },

    {
        id: 12,
        name: 'Đồ gia dụng',
        link: '/household',
        icon: 'fa-solid fa-house-laptop',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 13,
        name: 'Giày dép',
        link: '/shoe',
        icon: 'fa-solid fa-socks',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 14,
        name: 'Mũ',
        link: '/hat',
        icon: 'fa-solid fa-graduation-cap',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 15,
        name: 'Nội thất',
        link: '/interior',
        icon: 'fa-solid fa-cubes',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 7,
        name: 'Phụ kiện',
        link: '/accessory',
        icon: 'fa-solid fa-keyboard',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 6,
        name: 'Quần',
        link: '/trouser',
        icon: 'fa-solid fa-pants',
        color: 'bg-orange-100 text-orange-600',
    },
    {
        id: 16,
        name: 'Thể thao',
        link: '/sport',
        icon: 'fa-solid fa-basketball',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 5,
        name: 'Thiết bị',
        link: '/device',
        icon: 'fa-solid fa-keyboard',
        color: 'bg-orange-100 text-orange-600',
    },
    {
        id: 17,
        name: 'Tiện ích',
        link: '/ultity',
        icon: 'fa-solid fa-heart',
        color: 'bg-blue-100 text-blue-600',
    },
    {
        id: 18,
        name: 'Trang sức',
        link: '/jewelry',
        icon: 'fa-regular fa-alarm-clock',
        color: 'bg-blue-100 text-blue-600',
    },
];

export default catalogs;
